const data = [
  {
    "id": 2534,
    "dateListed": "2023-03-03 17:41:13",
    "title": "Lovely House with Mountain View",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 349000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Paris",
    "sqft": 4638,
    "bedrooms": 4,
    "bathrooms": 3,
    "parking": 4,
    "yearBuilt": 2006
  },
  {
    "id": 1278,
    "dateListed": "2018-03-20 22:24:21",
    "title": "Single Family House",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 499000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Barcelona",
    "sqft": 5638,
    "bedrooms": 5,
    "bathrooms": 3,
    "parking": 3,
    "yearBuilt": 2008
  },
  {
    "id": 5631,
    "dateListed": "2018-03-16 21:55:28",
    "title": "5 bedroom house in Sao Paulo",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 449000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Sao Paulo",
    "sqft": 5838,
    "bedrooms": 5,
    "bathrooms": 3,
    "parking": 4,
    "yearBuilt": 2003
  },
  {
    "id": 4720,
    "dateListed": "2018-02-28 23:37:28",
    "title": "3 bedroom house in Cartagena",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 350000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Cartagena",
    "sqft": 2638,
    "bedrooms": 3,
    "bathrooms": 2,
    "parking": 2,
    "yearBuilt": 2006
  },
  {
    "id": 6631,
    "dateListed": "2018-03-01 20:18:20",
    "title": "Beautiful traditional ranch in California",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 575000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "California",
    "sqft": 4638,
    "bedrooms": 4,
    "bathrooms": 4,
    "parking": 4,
    "yearBuilt": 2006
  },
  {
    "id": 4234,
    "dateListed": "2018-03-20 22:15:34",
    "title": "4 bedrooms with a spacious garage",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 475000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Ontario",
    "sqft": 2048,
    "bedrooms": 4,
    "bathrooms": 2,
    "parking": 2,
    "yearBuilt": 1840
  },
  {
    "id": 5130,
    "dateListed": "2018-03-19 20:53:04",
    "title": "Beautiful spacious 1306 sq ft Bungalow",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 374000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Alberta",
    "sqft": 1306,
    "bedrooms": 5,
    "bathrooms": 3,
    "parking": 4,
    "yearBuilt": 2001
  },
  {
    "id": 1125,
    "dateListed": "2018-03-01 19:59:05",
    "title": "EXQUISITE POND VIEW HOME",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 450000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Paris",
    "sqft": 1935,
    "bedrooms": 3,
    "bathrooms": 2,
    "parking": 2,
    "yearBuilt": 2001
  },
  {
    "id": 110,
    "dateListed": "2019-01-31 16:24:09",
    "title": "Meticulously maintained Lampman Family Home",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 199000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Saskatchewan",
    "sqft": 1204,
    "bedrooms": 5,
    "bathrooms": 3,
    "parking": 6,
    "yearBuilt": 1966
  },
  {
    "id": 10847,
    "dateListed": "2018-02-28 19:03:26",
    "title": "Charming updated gem",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin dictum convallis vehicula. Morbi ac gravida mi. Nullam aliquam ut lorem ut fringilla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur consequat magna risus, at tempus magna semper eget. Sed eget finibus nisl, ut pellentesque mi. Pellentesque vulputate ultricies posuere. Vestibulum sagittis at eros non accumsan. Proin nec sollicitudin ante, tempus dignissim velit. Quisque bibendum pharetra purus, in cursus tortor condimentum et. Etiam vel dictum lacus. Nulla non ligula at tortor cursus sollicitudin blandit ut sem.",
    "salePrice": 725000,
    "thumbnailURL": "https://dummyimage.com/150x150/AAF4EE/000000",
    "pictureURL": "https://dummyimage.com/350x350/AAF4EE/000000",
    "location": "Seattle",
    "sqft": 6194,
    "bedrooms": 4,
    "bathrooms": 2,
    "parking": 1,
    "yearBuilt": 1948
  }
]
export default data